### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Matnard** [umgbhalla/dotstow#4]
https://github.com/umgbhalla/dotstow/blob/9896d94ea0643911aa243dde3639c28556047bcb/base/misc/.xinitrc#L47

setxkbmap

**Comment by umgbhalla** [comment]
![](https://images-ext-1.discordapp.net/external/pNnrxgE3tZBq83wVlq6JL-dflyIa0p7E4EMi_TYx-i8/https/cdn.discordapp.com/emojis/861935609626492988.webp)
[fixed](https://github.com/umgbhalla/dotstow/commit/ca7598b050f1ad205eee0513254857982b873118)
